version: "3"
services:
  jnk:
    build: ./docker
    image: jenkins:latest
    container_name: jnkdock
    ports:
      - 18080:8080
    volumes:
#     - ./home:/var/jenkins_home
      - ./secrets:/var/jenkins_home/secrets