version: '3'
services:
  db:
#    image: mysql:5.7
    container_name: mysql-server
    build: 
      context: ./MySQLServer
      dockerfile: dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
#    ports:
#      - xx:xx
    environment:
      MYSQL_DATABASE:zabbix
      MYSQL_USER:zabbix
      MYSQL_PASSWORD:zabbix_pwd
      MYSQL_ROOT_PASSWORD:root_pwd
    volumes:
    networks:
      - zabbixnw
  gw:
    container_name: zabbix-java-gateway
    build: 
      context: ./Gateway
      dockerfile: dockerfile
    volumes:
    networks:
      - zabbixnw
  sv:
    container_name: zabbixserver
    build: 
      context: ./ZabbixServer
      dockerfile: dockerfile
    ports:
      - 10051:10051
    environment:
      DB_SERVER_HOST:mysql-server
      MYSQL_DATABASE:zabbix
      MYSQL_USER:zabbix
      MYSQL_PASSWORD:zabbix_pwd
      MYSQL_ROOT_PASSWORD:root_pwd
      ZBX_JAVAGATEWAY:zabbix-java-gateway
    volumes:
    networks:
      - zabbixnw
  nginx:
    container_name: nginx
    build: 
      context: ./Nginx
      dockerfile: dockerfile
    ports:
      - 80:80
    volumes:
    networks:
      - zabbixnw
networks:
  zabbixnw:
    external: true